name: Build Test - SWA-apps:Test-ACR

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        app:
#           - StaticWebAppsSamples/HugoClientDotNetCoreServer
#           - StaticWebAppsSamples/ReactClientNodeServer/app
          - StaticWebAppsSamples/nextjs-starter-main
#           - StaticWebAppsSamples/angular-basic-main
#           - StaticWebAppsSamples/blazor-basic-main/Client
#           - StaticWebAppsSamples/blazor-sample/Client
#           - StaticWebAppsSamples/blazor-starter-main/Client
#           - StaticWebAppsSamples/mongoose-starter-main
#           - StaticWebAppsSamples/nextjs-csr-ssg-isr
#           - StaticWebAppsSamples/nextjs-starter-main
#           - StaticWebAppsSamples/next-with-static-export
#           - StaticWebAppsSamples/nuxt-3-starter-main
#           - StaticWebAppsSamples/nuxtjs-starter-main
#           - StaticWebAppsSamples/react-basic-main
#           - StaticWebAppsSamples/roles-function-main
#           - StaticWebAppsSamples/StartupAdventurer-main
#           - StaticWebAppsSamples/svelte-basic-main
#           - StaticWebAppsSamples/vanilla-api-main
#           - StaticWebAppsSamples/vanilla-basic-main
#           - StaticWebAppsSamples/vue-basic-main
#           - StaticWebAppsSamples/hugo-example.github.io-master
#           - StaticWebAppsSamples/hugoBasicsExample-master
#           - StaticWebAppsSamples/sample-hugo-main
#           - StaticWebAppsSamples/vue-basic-main  
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          repository: microsoft/oryx
          ref: snehapar/Test-SWA-for-all-platforms
      # - uses: actions/cache@v3
      #   with:
      #    path: |
      #     .cache/go-build
      #     go/pkg/mod
      #    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #    restore-keys: |
      #      ${{ runner.os }}-go-    
      # - name: Install Azure-cli
      #   uses: elstudio/action-install-azure-cli@v1
      # - name: Log into registry
      #   uses: azure/login@v1
      #   with:
      #    creds: '${{ secrets.AZURE_CREDENTIALS }}'
      # - name: Log in to Azure Container Registry
      #   uses: docker/login-action@v2.0.0
      #   with: 
      #    registry: jamstacktest.azurecr.io
      #    username: ${{ secrets.AZURE_CLIENT_ID }}
      #    password: ${{ secrets.AZURE_CLIENT_SECRET }}   
      # - uses: int128/docker-build-cache-config-action@v1
      #   id: cache
      #   with:
      #     image: ghcr.io/${{ github.repository }}/cache
      # - uses: docker/build-push-action@v2
      #   id: build
      #   with:
      #     cache-from: ${{ steps.cache.outputs.cache-from }}
      #     cache-to: ${{ steps.cache.outputs.cache-to }}

      # - name: Build application - pre-bake node + python dependecies
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/build:azfunc-jamstack-debian-bullseye-Install-libedit oryx build /app 
      # - name: Build application - pre-bake node + python dependecies - pre-bake python + yarn
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/build:azfunc-jamstack-debian-bullseye-Install-libedit oryx build /app 
      # - name: Pull jamstack image from private ACR
      #   run: docker pull jamstacktest.azurecr.io/oryx/build:Pre-bake-node
      - name: Oryx build step
        uses: snehapar9/jamstacktest-composite-action-private-image@snehapar/oryx-build
        id: oryx-build
        with:
          app-location: ./tests/SampleApps/${{ matrix.app }} 
      # - name: Pull jamstack image from MCR
      #   run : docker pull mcr.microsoft.com/oryx/build:azfunc-jamstack-debian-bullseye-20221103.1
      # - name: Build application - jamstack-bullseye-20221103.1
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:azfunc-jamstack-debian-bullseye-20221103.1 oryx build /app
      #   run: docker run --rm --no-cache -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/build:azfunc-jamstack-debian-bullseye-Install-libedit oryx build /app 
      # - name: Build application - pre-bake node + python dependecies - pre-bake python + yarn
      #   run: docker run --rm --no-cache -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/build:Fix-sytax-errors oryx build /app 
      # - name: Build application - pre-bake node + python dependecies - pre-bake python + yarn + node
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/build:Pre-bake-node oryx build /app   
      # - name: Build application - jamstack-bullseye-20221103.1
      #   run: docker run --rm --no-cache -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:azfunc-jamstack-debian-bullseye-20221103.1 oryx build /app
      # - name: Build application - jamstack-bullseye
      #   run: docker run --rm --no-cache -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:azfunc-jamstack-debian-bullseye-20221214.1 oryx build /app    
      # - name: Build application - cli-bullseye
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/cli-bullseye:v2 oryx build /app
      # - name: Build application - jamstack-bullseye
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app mcr.microsoft.com/oryx/build:azfunc-jamstack-debian-bullseye-20221214.1 oryx build /app
      # - name: Build application - buildpack-deps-bullseye
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/samples:buildpack-deps-bullseye oryx build /app
      # - name: Build application - buildpack-deps-bullseye-scm
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/samples:buildpack-deps-bullseye-scm oryx build /app  
      # - name: Build application - buildpack-deps-bullseye-curl
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/samples:buildpack-deps-bullseye-curl oryx build /app   
      # - name: Pull docker image
      #   run: docker pull jamstacktest.azurecr.io/oryx/jamstack:azfunc-jamstack-debian-bullseye  

      # - name: Build application - cli-bullseye
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/cli-bullseye:v2 oryx build /app    
      # - name: Build application - pre-bake node + python dependecies
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/build:azfunc-jamstack-debian-bullseye-Install-libedit oryx build /app 
      # - name: Build application - cli-bullseye
      #   run: docker run --rm -v $(pwd)/tests/SampleApps/${{ matrix.app }}:/app jamstacktest.azurecr.io/oryx/cli-bullseye:v2 oryx build /app 
